name = input("이름을 입력하시오 : ")
print(name, "씨, 안녕하세요?")
print("파이썬에 오신 것을 환영합니다.")
num1 = int(input("첫 번째 정수를 입력하시오 : "))
num2 = int(input("두 번째 정수를 입력하시오 : "))
print(num1, "과 ", num2, "의 합은", num1 + num2, "입니다.")